### ISSUE TITLE
Guides labo's DB2 - code block taal aanpassen [2 martipoints]

### ISSUE THREAD

**Issue by martijnmeeldijk** [martijnmeeldijk/TI-oplossingen#43]
dit:
   _'''
   postgreSQL
   SELECT pg_size_pretty(pg_total_relation_size('ruimtereizen.bezoeken'));
   '''_

veranderen naar dit:
   _'''
   sql
   SELECT pg_size_pretty(pg_total_relation_size('ruimtereizen.bezoeken'));
   '''_
waar nodig
dan werkt syntax highlighting deftig

**Comment by ikbenignace** [comment]
Solved
#76

**Comment by martijnmeeldijk** [comment]
nog een fijne dag verder

**Comment by ikbenignace** [comment]
Uw muziek is zalig
